version: "3.7.9"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=praggregator
      - POSTGRES_USER=praggregatoruser
      - POSTGRES_PASSWORD=Z4dtOScE/RFqWhj1o74KSZ/A
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db