# Generated by Django 3.1.2 on 2020-10-15 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_offer_external_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='external_id',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
