# Generated by Django 3.1.2 on 2020-10-17 17:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0003_auto_20201015_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='historical_prices',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
