# Generated by Django 3.1.2 on 2020-10-17 18:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0004_offer_historical_prices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='historical_prices',
            field=models.JSONField(blank=True, default={}),
            preserve_default=False,
        ),
    ]
