# Generated by Django 3.1.2 on 2020-10-17 18:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0006_remove_offer_historical_prices'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='historical_values',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
