# Generated by Django 3.1.2 on 2020-10-17 18:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0007_offer_historical_values'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='historical_values',
            new_name='historical_prices',
        ),
    ]
